import type { CompleteZeduxLoggerLocalOptions } from '../types/ZeduxLoggerLocalOptions.js';
import { DEFAULT_ZEDUX_LOGGER_COLORS } from './default-zedux-logger-colors.js';

export const DEFAULT_ZEDUX_LOGGER_LOCAL_OPTIONS: CompleteZeduxLoggerLocalOptions =
  {
    eventsToShow: {
      change: true,
      cycle: true,
      edge: false,
      error: true,
      invalidate: true,
      promiseChange: true,
      resetStart: true,
      resetEnd: true,
      runStart: false,
      runEnd: false,
    },
    console,
    oneLineLogs: false,
    showColors: true,
    colors: DEFAULT_ZEDUX_LOGGER_COLORS,
    showInSummary: {
      showEmoji: true,
      showEcosystemName: false,
      showAtomName: true,
      showSummary: true,
      showOperation: true,
      showTtl: true,
      showOldState: true,
      showNewState: true,
      showObserverName: true,
      showWaitingPromises: true,
      showExecutionTime: true,
    },
    showInDetails: {
      showEvent: true,
      showOldState: true,
      showNewState: true,
      showWaitingPromises: true,
      showStateDiff: true,
      showReasons: true,
      showError: true,
      showNode: true,
      showObserver: true,
      showSources: true,
      showObservers: true,
      showEcosystem: true,
      showGraph: true,
      showSnapshot: true,
      showExecutionTime: true,
    },
    executionTimeOptions: {
      slowThresholdMs: 50,
      verySlowThresholdMs: 100,
      warnInConsoleIfSlow: true,
      errorInConsoleIfVerySlow: true,
      onSlowEvaluation: null,
      onVerySlowEvaluation: null,
    },
    graphOptions: {
      showTopDownGraph: true,
      showBottomUpGraph: true,
      showFlatGraph: true,
      showByNamespacesGraph: true,
      groupCollapseGraph: true,
    },
    snapshotOptions: {
      groupCollapseSnapshot: true,
    },
    diffOptions: {
      groupCollapseStateDiff: true,
    },
    deobfuscateSingleLetters: true,
    deobfuscateSingleLettersOptions: {
      deobfuscateEvents: true,
      deobfuscateGraphNodes: true,
      deobfuscateReasons: true,
      deobfuscateEcosystem: true,
    },
  };
